mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [

    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<comment_id>[0-9]+)/vote/$', views.vote, name='vote'),

    #Create comment polls/new
   	url(r'^new/$', views.StatementCreate.as_view(), name='comment-new'),
   	#Edit comment polls/2
   	url(r'^comment/(?P<pk>[0-9]+)/$', views.StatementUpdate.as_view(), name='comment-update'),
   	#Delete comment
   	url(r'^comment/(?P<pk>[0-9]+)/delete/$', views.StatementDelete.as_view(), name='comment-delete'),

   	#Create Counter Argument
   	url(r'^new/Counter-Argument/(?P<pk>[0-9]+)/$', views.CounterArgCreate.as_view(), name='counter-argument-new'),
]

mysite/polls/models.py
import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.core.urlresolvers import reverse


class Comment(models.Model):
    comment_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('polls:index' )
    def __str__(self):
        return self.comment_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.put_date <= now


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    def __str__(self):
    	return self.choice_text
    def get_absolute_url(self):
        return reverse('polls:index' )

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Comment, Choice

# Create your views here.

#Generics for Problematic Statement
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_comment_list'

    def get_queryset(self):
        """Return the last five published comments."""
        return Comment.objects.order_by('-pub_date')[:10]


class DetailView(generic.DetailView):
    model = Comment
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Comment
    template_name = 'polls/results.html'

class NewStatementView(generic.DetailView):
	model = Comment
	template_name = 'polls/comment_form.html'

# CRUD functionality for Comments
class StatementCreate(CreateView):
	model = Comment
	fields = ['comment_text']

class StatementUpdate(UpdateView):
	model = Comment
	fields = ['comment_text']

class StatementDelete(DeleteView):
	model = Comment
	success_url = reverse_lazy('polls:index')

#Generic for Counter Argument

class CounterArgCreate(CreateView):
    model = Choice
    fields = ['comment','choice_text',]

#View for Voting Function


def vote(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    try:
        selected_choice = comment.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'comment': comment,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(comment.id,)))

# Leave the rest of the views (detail, results, vote) unchanged

mysite/polls/templates/polls/choice_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>Counter Argument Entry</h1>

<form action="" method="post">
	{% csrf_token %}
	{% include 'polls/form_templates.html'%}


<input type='submit' value='Create'>

</form>

mysite/polls/templates/polls/comment_confirm_delete.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h6>Comfirm Delete of Following Statment:</h6>
<h1>{{comment.comment_text}}</h1>
<form method="POST" action="{% url 'polls:comment-delete' comment.id %}">
   {% csrf_token %} <br>
   <input type="submit" value="DELETE">
</form>

mysite/polls/templates/polls/comment_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>Problematic Statement Entry</h1>

<form action="" method="post">
	{% csrf_token %}
	{% include 'polls/form_templates.html'%}


<input type='submit' value='Create'>

</form>

mysite/polls/templates/polls/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ comment.comment_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' comment.id %}" method="post">
{% csrf_token %}
{% for choice in comment.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

<a href="{% url 'polls:counter-argument-new' comment.id%}"> Create Counter Argument </a>

mysite/polls/templates/polls/form_templates.html
{% for field in form%}
	{{field.errors}}
	<label> {{ field.label_tag}}</label>
	<div>{{field}}</div>

{% endfor %}

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_comment_list %}
<h1>List of Most Recently Uploaded Statements</h1>
    <ul>
    {% for comment in latest_comment_list %}
        <li><a href="{% url 'polls:detail' comment.id %}">{{ comment.comment_text }} </a> <br>
        	<a href="{% url 'polls:comment-delete' comment.id%}"> Delete</a>
        	<a href="{% url 'polls:comment-update' comment.id%}"> Edit</a>
	
        </li>
    {% endfor %}

<h4><a href="{% url 'polls:comment-new' %}"</a>Add new Problematic Statement</h4>

    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/new.html
<h1>New Problematic Statement Entry</h1>

<form action="{% url 'polls:new' comment.id %}" method="post">

 <dt>Source:</dt>
      <dd><input type ='text' size='30' name='name' required></dd>

<dt>Statement:</dt>
      <dd><textarea name = 'description' rows='5' cols='40' required></textarea></dd>

<input type='submit' value='Create'>

</form>

mysite/polls/templates/polls/new_counter_arg.html
<p>Create Counter Argument for {{comment.comment_text}}</p>

<form action="" method="post">
	{% csrf_token %}
	<textarea rows = "4" cols ="50"> 

	</textarea>

<br>
<input type='submit' value='Create'>

</form>

mysite/polls/templates/polls/results.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<h1>{{ comment.comment_text }}</h1>

<ul>
{% for choice in comment.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    
{% endfor %}
</ul>

<a href="{% url 'polls:detail' comment.id %}">Vote again?</a>